---

- name: Create Load Balancer
  ec2_elb_lb:
    name: "http-balancer"
    state: present
    subnets: "{{ vpc_subnet_id }}"
    region: "{{ aws_region }}"
    security_group_names: webserver
    listeners:
      - protocol: http
        load_balancer_port: 80
        instance_port: 80
  register: elb_describe

- debug: var=elb_describe

- name: Set the ELB name
  set_fact:
    elb_name: "{{ item }}"
  with_items: "{{ elb_describe.elb.name }}"

#- debug: var=elb_name

#- debug: var=webserver_ids

- name: Pause for 10 seconds to get apaches ready
  pause: 
    seconds: 10

- name: Register webservers with created ELB
  ec2_elb:
    instance_id: "{{ item }}"
    region: "{{ aws_region }}"
    ec2_elbs: "{{ elb_name }}"
    state: present
  with_items: "{{ webserver_ids.stdout_lines }}"
